# Generated by Django 3.1.2 on 2020-10-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ame',
            new_name='name',
        ),
    ]
